---
- hosts: all
  tasks:
    - name: Update yum update
      yum: name=* state=latest
      become: yes
      become_user: root
    - name: Install EPEL repository
      command: amazon-linux-extras install -y epel
      become: yes
      become_user: root
    - name: ensure nginx is at the latest version
      yum: name=nginx state=latest
      become: yes
      become_user: root
    - name: start nginx
      become: yes
      become_user: root
      service:
          name: nginx
          state: started
